<?php

namespace ContainerFIPCB80;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BXUgyVmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BXUgyVm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BXUgyVm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'matching' => ['privates', '.errored..service_locator.BXUgyVm.App\\Entity\\Matching', NULL, 'Cannot autowire service ".service_locator.BXUgyVm": it needs an instance of "App\\Entity\\Matching" but this type has been excluded in "config/services.yaml".'],
        ], [
            'matching' => 'App\\Entity\\Matching',
        ]);
    }
}
