<?php

namespace ContainerFIPCB80;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ys3dFlYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ys3dFlY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ys3dFlY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'matchingRepository' => ['privates', 'App\\Repository\\MatchingRepository', 'getMatchingRepositoryService', true],
        ], [
            'matchingRepository' => 'App\\Repository\\MatchingRepository',
        ]);
    }
}
