controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_matching_index:
    path: /matching
    controller: App\Controller\MatchingController::index
