<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_font' => [['fontName'], ['_controller' => 'web_profiler.controller.profiler::fontAction'], [], [['text', '.woff2'], ['variable', '/', '[^/\\.]++', 'fontName', true], ['text', '/_profiler/font']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/home']], [], [], []],
    'app_matching_new' => [[], ['_controller' => 'App\\Controller\\MatchingController::new'], [], [['text', '/matching/new']], [], [], []],
    'app_matching_show' => [['id'], ['_controller' => 'App\\Controller\\MatchingController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/matching']], [], [], []],
    'app_matching_edit' => [['id'], ['_controller' => 'App\\Controller\\MatchingController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/matching']], [], [], []],
    'app_matching_delete' => [['id'], ['_controller' => 'App\\Controller\\MatchingController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/matching']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\UserController::register'], [], [['text', '/register']], [], [], []],
    'app_matching_index' => [[], ['_controller' => 'App\\Controller\\MatchingController::index'], [], [['text', '/matching']], [], [], []],
    'App\Controller\HomeController::index' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/home']], [], [], []],
    'App\Controller\MatchingController::index' => [[], ['_controller' => 'App\\Controller\\MatchingController::index'], [], [['text', '/matching']], [], [], []],
    'App\Controller\MatchingController::new' => [[], ['_controller' => 'App\\Controller\\MatchingController::new'], [], [['text', '/matching/new']], [], [], []],
    'App\Controller\MatchingController::show' => [['id'], ['_controller' => 'App\\Controller\\MatchingController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/matching']], [], [], []],
    'App\Controller\MatchingController::edit' => [['id'], ['_controller' => 'App\\Controller\\MatchingController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/matching']], [], [], []],
    'App\Controller\MatchingController::delete' => [['id'], ['_controller' => 'App\\Controller\\MatchingController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/matching']], [], [], []],
    'App\Controller\UserController::register' => [[], ['_controller' => 'App\\Controller\\UserController::register'], [], [['text', '/register']], [], [], []],
];
