<?php

namespace ContainerSjNCMDm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U8IWU43Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.u8IWU43' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u8IWU43'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'matching' => ['privates', '.errored..service_locator.u8IWU43.App\\Entity\\Matching', NULL, 'Cannot autowire service ".service_locator.u8IWU43": it needs an instance of "App\\Entity\\Matching" but this type has been excluded in "config/services.yaml".'],
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
        ], [
            'entityManager' => '?',
            'matching' => 'App\\Entity\\Matching',
            'validator' => '?',
        ]);
    }
}
