<?php

namespace ContainerSjNCMDm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMatchingService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.BXUgyVm.App\Entity\Matching' shared service.
     *
     * @return \App\Entity\Matching
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.BXUgyVm": it needs an instance of "App\\Entity\\Matching" but this type has been excluded in "config/services.yaml".');
    }
}
